name: csven
version: '0.1.2'
summary: Order English words
description: CSVEN allows you to add an English word to mess it up and put it back together to learn how to write it through a game

base: core24
confinement: strict
grade: stable

apps:
  csven:
    command: bin/csven
    desktop: ${SNAPCRAFT_STAGE}/share/applications/io.github.rsvzz.csven.desktop
    extensions: [gnome]
    common-id: io.github.rsvzz.csven
    plugs: 
    - x11
    - wayland
    - desktop
    - desktop-legacy

parts:
  questk:
    plugin: meson
    source: https://github.com/rsvzz/libquestk.git
    source-type: git
    source-tag: 0.0.1
    meson-parameters:
      - --prefix=/
      - --buildtype=release
    build-packages:
      - meson

  csven:
    plugin: meson
    source: https://github.com/rsvzz/csven.git
    source-type: git
    source-tag: 0.1.1
    meson-parameters:
      - --prefix=/
      - --buildtype=release
    after: [questk]
    build-environment:
      - C_INCLUDE_PATH: ${SNAPCRAFT_STAGE}/include
      - LIBRARY_PATH: ${SNAPCRAFT_STAGE}/lib/x86_64-linux-gnu
    build-packages:
      - meson
      - ninja-build
    override-build: |
      snapcraftctl build
      rm -r ${SNAPCRAFT_PART_INSTALL}/share/applications/io.github.rsvzz.csven.desktop
    
  csven-files:
    source: .
    plugin: dump
    override-build: |
      mkdir ${SNAPCRAFT_PART_INSTALL}/share/applications -p
      cp ${SNAPCRAFT_PART_BUILD}/data/io.github.rsvzz.csven.desktop ${SNAPCRAFT_PART_INSTALL}/share/applications