name: csven
version: '0.0.6'
summary: Order English words
description: CSVEN allows you to add an English word to mess it up and put it back together to learn how to write it through a game

base: core24
confinement: strict
grade: stable

apps:
  csven:
    command: bin/csven
    desktop: ${SNAPCRAFT_STAGE}/share/applications/io.github.rsvzz.csven.desktop
    plugs: 
    - x11
    - wayland
    - desktop
    - desktop-legacy

parts:
  questk:
    plugin: meson
    source: https://github.com/rsvzz/libquestk.git
    source-type: git
    source-tag: 0.0.1
    meson-parameters:
      - --prefix=/
      - --buildtype=release
    build-packages:
      - meson
  csven-files:
    source: .
    plugin: dump
    override-build: |
      mkdir ${SNAPCRAFT_PART_INSTALL}/share/applications -p
      mkdir ${SNAPCRAFT_PART_INSTALL}/share/icons/hicolor/scalable/apps -p
      cp ${SNAPCRAFT_PART_BUILD}/data/io.github.rsvzz.csven.desktop ${SNAPCRAFT_PART_INSTALL}/share/applications
      cp ${SNAPCRAFT_PART_BUILD}/data/io.github.rsvzz.csven.png ${SNAPCRAFT_PART_INSTALL}/share/icons/hicolor/scalable/apps

  csven:
    plugin: meson
    source: https://github.com/rsvzz/c_sven.git
    source-type: git
    source-tag: 0.0.6
    meson-parameters:
      - --prefix=/
      - --buildtype=release
    after: [questk]
    build-environment:
      - C_INCLUDE_PATH: ${SNAPCRAFT_STAGE}/include
      - LIBRARY_PATH: ${SNAPCRAFT_STAGE}/lib/x86_64-linux-gnu
    build-packages:
      - meson
      - ninja-build
      - libgtk-4-dev
    stage-packages:
      - libgtk-4-1
      - fontconfig