name: csven
version: '0.1.13'
summary: Order English words
description: CSVEN allows you to add an English word to mess it up and put it back together to learn how to write it through a game
base: core24
confinement: strict
grade: stable
license: GPL-3.0-or-later
compression: lzo

platforms: 
  amd64:
  arm64:
  armhf:

apps:
  csven:
    command: bin/csven
    desktop: share/applications/io.github.rsvzz.csven.desktop
    extensions: [gnome]
    common-id: io.github.rsvzz.csven
    slots: [csven-dbs]
    environment:
      GTK_THEME: Adwaita
      XDG_DATA_DIRS: "$SNAP/usr/share:$SNAP/share:${XDG_DATA_DIRS:-/usr/local/share:/usr/share}"
      GTK_DATA_PREFIX: $SNAP

    plugs: 
      - x11
      - wayland
      - desktop-legacy
      - desktop

parts:
  csven:
    plugin: meson
    source: https://github.com/rsvzz/csven.git
    source-type: git
    source-tag: 0.1.14
    meson-parameters:
      - --prefix=/
      - --buildtype=release
    build-environment:
      - C_INCLUDE_PATH: ${SNAPCRAFT_STAGE}/include
      - LIBRARY_PATH: ${SNAPCRAFT_STAGE}/lib/x86_64-linux-gnu
    build-packages:
      - meson
    override-build: |
      snapcraftctl build
      rm -r ${SNAPCRAFT_PART_INSTALL}/share/applications/io.github.rsvzz.csven.desktop
      cp -v ${SNAPCRAFT_PROJECT_DIR}/data/io.github.rsvzz.csven.desktop ${SNAPCRAFT_PART_INSTALL}/share/applications

slots:
  csven-dbs:
    interface: dbus
    bus: session
    name: io.github.rsvzz.csven